# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: postgres
    restart: always
    volumes:
      - postgre_data:/var/lib/postgresql/data
    networks:
      - db_access
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgre_data:

networks:
  db_access:
