import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import Header from "./components/header/Header";

const inter = Inter({ subsets: ["latin"] });

//TODO : Mettre en place le footer

export const metadata: Metadata = {
  title: "Valym app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en" data-theme="mytheme">
        <body className={inter.className}>
          <div className="h-screen flex flex-col">
            <div className="fixed z-10">
              <Header />
            </div>
            <div className="sm:px-10 pt-5 mt-14">{children}</div>
            <div className="h-full flex flex-col justify-end">
              <div>Footer</div>
            </div>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
